import type { EntitySpec } from "@/components/seo/RecordDialog";

const STATUS = (options: string[]) => ({ statusField: "status", statusOptions: options });

/** Field-level definitions for every editable SEO entity. */
export const entities = {
  pages: {
    table: "seo_pages",
    label: "Page",
    titleField: "url",
    ...STATUS(["indexed", "not_indexed", "excluded", "pending"]),
    fields: [
      { name: "url", label: "URL", required: true, placeholder: "/products/pos" },
      { name: "title", label: "Title", required: true },
      { name: "meta_title", label: "Meta title" },
      { name: "meta_description", label: "Meta description", type: "textarea" },
      { name: "h1", label: "H1" },
      { name: "canonical_url", label: "Canonical URL" },
      { name: "word_count", label: "Word count", type: "number", default: 0 },
      { name: "seo_score", label: "SEO score", type: "number", default: 0, max: 100 },
      {
        name: "page_type",
        label: "Page type",
        type: "select",
        options: ["landing", "product", "blog", "docs", "legal", "other"],
        default: "landing",
      },
      {
        name: "index_status",
        label: "Index status",
        type: "select",
        options: ["indexed", "not_indexed", "excluded", "pending"],
        default: "indexed",
      },
      { name: "issues_count", label: "Issues", type: "number", default: 0, editOnly: true },
    ],
  },
  keywords: {
    table: "seo_keywords",
    label: "Keyword",
    titleField: "keyword",
    ...STATUS(["tracking", "paused", "won", "lost"]),
    fields: [
      { name: "keyword", label: "Keyword", required: true },
      { name: "target_url", label: "Target URL", placeholder: "/pos-software" },
      { name: "position", label: "Position", type: "number", default: 0 },
      { name: "previous_position", label: "Previous position", type: "number", editOnly: true },
      { name: "search_volume", label: "Monthly search volume", type: "number", default: 0 },
      { name: "difficulty", label: "Difficulty (0–100)", type: "number", default: 0, max: 100 },
      { name: "cpc", label: "CPC (USD)", type: "number", step: 0.01, default: 0 },
      {
        name: "intent",
        label: "Intent",
        type: "select",
        options: ["informational", "commercial", "transactional", "navigational"],
        default: "informational",
      },
      { name: "industry", label: "Industry" },
      { name: "country", label: "Country code", placeholder: "US" },
      { name: "region", label: "Region", default: "global", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["tracking", "paused", "won", "lost"],
        default: "tracking",
      },
    ],
  },
  metaRules: {
    table: "seo_meta_rules",
    label: "Meta rule",
    titleField: "name",
    ...STATUS(["active", "paused", "draft"]),
    fields: [
      { name: "name", label: "Rule name", required: true },
      { name: "url_pattern", label: "URL pattern", required: true, placeholder: "/products/*" },
      { name: "title_template", label: "Title template", required: true },
      { name: "description_template", label: "Description template", type: "textarea", required: true },
      { name: "og_image_template", label: "OG image template" },
      { name: "priority", label: "Priority", type: "number", default: 1 },
      { name: "applies_to", label: "Applies to (pages)", type: "number", default: 0, editOnly: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["active", "paused", "draft"],
        default: "active",
      },
    ],
  },
  indexing: {
    table: "seo_indexing_records",
    label: "URL",
    titleField: "url",
    statusField: "index_state",
    statusOptions: ["discovered", "indexed", "not_indexed", "excluded_canonical", "excluded_redirect"],
    fields: [
      { name: "url", label: "URL", required: true },
      {
        name: "source",
        label: "Source",
        type: "select",
        options: ["sitemap", "discovered", "manual", "backlink"],
        default: "manual",
      },
      {
        name: "crawl_status",
        label: "Crawl status",
        type: "select",
        options: ["queued", "pending", "crawled", "failed"],
        default: "queued",
      },
      {
        name: "index_state",
        label: "Index state",
        type: "select",
        options: [
          "discovered",
          "indexed",
          "not_indexed",
          "excluded_canonical",
          "excluded_redirect",
        ],
        default: "discovered",
      },
      { name: "http_status", label: "HTTP status", type: "number", default: 200 },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  issues: {
    table: "seo_issues",
    label: "Issue",
    titleField: "page_url",
    ...STATUS(["open", "in_progress", "resolved", "ignored"]),
    fields: [
      { name: "page_url", label: "Page URL", required: true },
      { name: "issue_type", label: "Issue type", required: true },
      {
        name: "category",
        label: "Category",
        type: "select",
        options: ["on-page", "technical", "content", "off-page", "performance"],
        default: "technical",
      },
      {
        name: "severity",
        label: "Severity",
        type: "select",
        options: ["critical", "high", "medium", "low"],
        default: "medium",
      },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "fix_suggestion", label: "Fix suggestion", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["open", "in_progress", "resolved", "ignored"],
        default: "open",
      },
    ],
  },
  backlinks: {
    table: "seo_backlinks",
    label: "Backlink",
    titleField: "source_domain",
    ...STATUS(["active", "lost", "pending", "toxic"]),
    fields: [
      { name: "source_domain", label: "Source domain", required: true },
      { name: "source_url", label: "Source URL", required: true },
      { name: "target_url", label: "Target URL", required: true },
      { name: "anchor_text", label: "Anchor text" },
      { name: "domain_authority", label: "Domain authority", type: "number", default: 0, max: 100 },
      {
        name: "link_type",
        label: "Link type",
        type: "select",
        options: ["dofollow", "nofollow", "ugc", "sponsored"],
        default: "dofollow",
      },
      { name: "spam_score", label: "Spam score", type: "number", default: 0, max: 100 },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["active", "lost", "pending", "toxic"],
        default: "active",
      },
    ],
  },
  competitors: {
    table: "seo_competitors",
    label: "Competitor",
    titleField: "name",
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "domain", label: "Domain", required: true, placeholder: "competitor.com" },
      { name: "region", label: "Region", default: "global", required: true },
      { name: "visibility_score", label: "Visibility score", type: "number", step: 0.1, default: 0 },
      { name: "keywords_count", label: "Keywords", type: "number", default: 0 },
      { name: "backlinks_count", label: "Backlinks", type: "number", default: 0 },
      { name: "traffic_estimate", label: "Traffic estimate", type: "number", default: 0 },
      { name: "domain_authority", label: "Domain authority", type: "number", default: 0, max: 100 },
    ],
  },
  content: {
    table: "seo_content_items",
    label: "Content item",
    titleField: "title",
    ...STATUS(["draft", "in_review", "scheduled", "published", "archived"]),
    fields: [
      { name: "title", label: "Title", required: true },
      {
        name: "content_type",
        label: "Content type",
        type: "select",
        options: ["blog", "landing", "product", "case-study", "guide"],
        default: "blog",
      },
      { name: "target_keyword", label: "Target keyword" },
      { name: "body", label: "Body", type: "textarea" },
      { name: "word_count", label: "Word count", type: "number", default: 0 },
      { name: "seo_score", label: "SEO score", type: "number", default: 0, max: 100 },
      { name: "url", label: "URL" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["draft", "in_review", "scheduled", "published", "archived"],
        default: "draft",
      },
    ],
  },
  leads: {
    table: "seo_leads",
    label: "Lead",
    titleField: "full_name",
    statusField: "stage",
    statusOptions: ["new", "qualified", "contacted", "proposal", "won", "lost"],
    fields: [
      { name: "full_name", label: "Full name", required: true },
      { name: "company", label: "Company" },
      { name: "email", label: "Email", required: true },
      { name: "phone", label: "Phone" },
      { name: "country", label: "Country" },
      {
        name: "source_channel",
        label: "Source channel",
        type: "select",
        options: ["organic", "paid", "social", "referral", "direct", "email"],
        default: "organic",
      },
      { name: "source_keyword", label: "Source keyword" },
      { name: "landing_url", label: "Landing URL" },
      { name: "score", label: "Score", type: "number", default: 0, max: 100 },
      {
        name: "stage",
        label: "Stage",
        type: "select",
        options: ["new", "qualified", "contacted", "proposal", "won", "lost"],
        default: "new",
      },
      { name: "estimated_value", label: "Estimated value (USD)", type: "number", default: 0 },
    ],
  },
  ads: {
    table: "seo_ad_campaigns",
    label: "Ad campaign",
    titleField: "name",
    ...STATUS(["active", "paused", "draft", "ended"]),
    fields: [
      { name: "name", label: "Campaign name", required: true },
      {
        name: "channel",
        label: "Channel",
        type: "select",
        options: ["google", "meta", "linkedin", "bing", "youtube"],
        default: "google",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["active", "paused", "draft", "ended"],
        default: "draft",
      },
      { name: "budget", label: "Budget (USD)", type: "number", default: 0 },
      { name: "spend", label: "Spend (USD)", type: "number", default: 0, editOnly: true },
      { name: "impressions", label: "Impressions", type: "number", default: 0, editOnly: true },
      { name: "clicks", label: "Clicks", type: "number", default: 0, editOnly: true },
      { name: "conversions", label: "Conversions", type: "number", default: 0, editOnly: true },
      { name: "starts_on", label: "Starts on", type: "date" },
      { name: "ends_on", label: "Ends on", type: "date" },
    ],
  },
  email: {
    table: "seo_email_campaigns",
    label: "Email campaign",
    titleField: "name",
    ...STATUS(["draft", "scheduled", "sending", "sent", "paused"]),
    fields: [
      { name: "name", label: "Campaign name", required: true },
      { name: "segment", label: "Segment", required: true, default: "all-leads" },
      { name: "subject", label: "Subject line", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["draft", "scheduled", "sending", "sent", "paused"],
        default: "draft",
      },
      { name: "scheduled_at", label: "Scheduled at", type: "datetime" },
      { name: "sent_count", label: "Sent", type: "number", default: 0, editOnly: true },
      { name: "opened_count", label: "Opened", type: "number", default: 0, editOnly: true },
      { name: "clicked_count", label: "Clicked", type: "number", default: 0, editOnly: true },
      { name: "replied_count", label: "Replied", type: "number", default: 0, editOnly: true },
    ],
  },
  social: {
    table: "seo_social_posts",
    label: "Social post",
    titleField: "content",
    ...STATUS(["draft", "scheduled", "published", "failed"]),
    fields: [
      {
        name: "platform",
        label: "Platform",
        type: "select",
        options: ["linkedin", "x", "facebook", "instagram", "youtube"],
        default: "linkedin",
      },
      { name: "content", label: "Post content", type: "textarea", required: true },
      { name: "link_url", label: "Link URL" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["draft", "scheduled", "published", "failed"],
        default: "draft",
      },
      { name: "scheduled_at", label: "Scheduled at", type: "datetime" },
      { name: "impressions", label: "Impressions", type: "number", default: 0, editOnly: true },
      { name: "engagements", label: "Engagements", type: "number", default: 0, editOnly: true },
    ],
  },
  reels: {
    table: "seo_reels",
    label: "Reel",
    titleField: "title",
    ...STATUS(["draft", "rendering", "ready", "published"]),
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "prompt", label: "Prompt", type: "textarea", required: true },
      { name: "script", label: "Script", type: "textarea" },
      {
        name: "platform",
        label: "Platform",
        type: "select",
        options: ["instagram", "youtube", "tiktok", "linkedin"],
        default: "instagram",
      },
      { name: "duration_seconds", label: "Duration (seconds)", type: "number", default: 30 },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["draft", "rendering", "ready", "published"],
        default: "draft",
      },
      { name: "views", label: "Views", type: "number", default: 0, editOnly: true },
    ],
  },
  products: {
    table: "seo_product_entries",
    label: "Product entry",
    titleField: "product_name",
    ...STATUS(["draft", "review", "published"]),
    fields: [
      { name: "product_name", label: "Product name", required: true },
      { name: "category", label: "Category", required: true },
      { name: "target_keywords", label: "Target keywords", type: "tags" },
      { name: "meta_title", label: "Meta title" },
      { name: "meta_description", label: "Meta description", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["draft", "review", "published"],
        default: "draft",
      },
    ],
  },
  automations: {
    table: "seo_automations",
    label: "Automation",
    titleField: "name",
    ...STATUS(["active", "paused", "error"]),
    fields: [
      { name: "name", label: "Name", required: true },
      {
        name: "automation_type",
        label: "Type",
        type: "select",
        options: ["on-page", "technical", "rank-tracking", "content", "reporting"],
        default: "on-page",
      },
      { name: "description", label: "Description", type: "textarea" },
      {
        name: "schedule",
        label: "Schedule",
        type: "select",
        options: ["hourly", "daily", "weekly", "monthly"],
        default: "daily",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["active", "paused", "error"],
        default: "active",
      },
      { name: "next_run_at", label: "Next run", type: "datetime" },
    ],
  },
  flows: {
    table: "seo_automation_flows",
    label: "Flow",
    titleField: "name",
    ...STATUS(["active", "paused", "draft"]),
    fields: [
      { name: "name", label: "Flow name", required: true },
      { name: "trigger_event", label: "Trigger event", required: true, placeholder: "lead.created" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["active", "paused", "draft"],
        default: "active",
      },
    ],
  },
  alerts: {
    table: "seo_alerts",
    label: "Alert",
    titleField: "title",
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "message", label: "Message", type: "textarea", required: true },
      {
        name: "category",
        label: "Category",
        type: "select",
        options: ["ranking", "technical", "content", "traffic", "security"],
        default: "technical",
      },
      {
        name: "severity",
        label: "Severity",
        type: "select",
        options: ["critical", "high", "medium", "low", "info"],
        default: "medium",
      },
      { name: "acknowledged", label: "Acknowledged", type: "boolean", default: false },
    ],
  },
  technical: {
    table: "seo_technical_checks",
    label: "Technical check",
    titleField: "name",
    ...STATUS(["pass", "warning", "fail"]),
    fields: [
      { name: "name", label: "Check name", required: true },
      {
        name: "category",
        label: "Category",
        type: "select",
        options: ["crawlability", "performance", "security", "structured-data", "mobile"],
        default: "crawlability",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["pass", "warning", "fail"],
        default: "pass",
      },
      { name: "detail", label: "Detail", type: "textarea" },
      { name: "affected_urls", label: "Affected URLs", type: "number", default: 0 },
    ],
  },
  integrations: {
    table: "seo_integrations",
    label: "Integration",
    titleField: "display_name",
    ...STATUS(["connected", "disconnected", "error", "pending"]),
    fields: [
      { name: "provider", label: "Provider key", required: true, placeholder: "google_search_console" },
      { name: "display_name", label: "Display name", required: true },
      {
        name: "category",
        label: "Category",
        type: "select",
        options: ["analytics", "search", "ads", "social", "crm", "email"],
        default: "analytics",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["connected", "disconnected", "error", "pending"],
        default: "disconnected",
      },
    ],
  },
  suggestions: {
    table: "seo_ai_suggestions",
    label: "Suggestion",
    titleField: "title",
    ...STATUS(["pending", "accepted", "applied", "dismissed"]),
    fields: [
      { name: "title", label: "Title", required: true },
      {
        name: "target_type",
        label: "Target type",
        type: "select",
        options: ["site", "page", "keyword", "content"],
        default: "site",
      },
      { name: "target_ref", label: "Target reference" },
      { name: "suggestion", label: "Suggestion", type: "textarea", required: true },
      {
        name: "impact",
        label: "Impact",
        type: "select",
        options: ["high", "medium", "low"],
        default: "medium",
      },
      { name: "confidence", label: "Confidence", type: "number", default: 80, max: 100 },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["pending", "accepted", "applied", "dismissed"],
        default: "pending",
      },
    ],
  },
  reports: {
    table: "seo_reports",
    label: "Report",
    titleField: "name",
    ...STATUS(["generating", "ready", "failed"]),
    fields: [
      { name: "name", label: "Report name", required: true },
      {
        name: "report_type",
        label: "Type",
        type: "select",
        options: ["weekly", "monthly", "quarterly", "campaign", "custom"],
        default: "monthly",
      },
      { name: "period_start", label: "Period start", type: "date", required: true },
      { name: "period_end", label: "Period end", type: "date", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["generating", "ready", "failed"],
        default: "ready",
      },
    ],
  },
  inbox: {
    table: "seo_inbox_messages",
    label: "Message",
    titleField: "contact_name",
    ...STATUS(["unread", "read", "replied", "escalated", "archived"]),
    fields: [
      {
        name: "channel",
        label: "Channel",
        type: "select",
        options: ["email", "chat", "whatsapp", "form", "social"],
        default: "email",
      },
      { name: "contact_name", label: "Contact name", required: true },
      { name: "contact_handle", label: "Contact handle" },
      { name: "message", label: "Message", type: "textarea", required: true },
      { name: "auto_reply", label: "Auto reply", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["unread", "read", "replied", "escalated", "archived"],
        default: "unread",
      },
    ],
  },
  comments: {
    table: "seo_social_comments",
    label: "Comment",
    titleField: "author",
    ...STATUS(["pending", "replied", "hidden", "escalated"]),
    fields: [
      {
        name: "platform",
        label: "Platform",
        type: "select",
        options: ["linkedin", "x", "facebook", "instagram", "youtube"],
        default: "linkedin",
      },
      { name: "author", label: "Author", required: true },
      { name: "comment", label: "Comment", type: "textarea", required: true },
      {
        name: "sentiment",
        label: "Sentiment",
        type: "select",
        options: ["positive", "neutral", "negative"],
        default: "neutral",
      },
      { name: "auto_reply", label: "Auto reply", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["pending", "replied", "hidden", "escalated"],
        default: "pending",
      },
    ],
  },
} satisfies Record<string, EntitySpec>;

export type EntityKey = keyof typeof entities;
