CREATE TABLE IF NOT EXISTS public.accessibility_compliance (alt_text_pass boolean, auditor_notes text, color_contrast_pass boolean, created_at timestamptz DEFAULT now(), id uuid PRIMARY KEY DEFAULT gen_random_uuid(), issues_found numeric, issues_resolved numeric, keyboard_nav_pass boolean, language_support text[], last_audit_date text, page_url text, screen_reader_pass boolean, status text, wcag_level text);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.accessibility_compliance TO authenticated; GRANT ALL ON public.accessibility_compliance TO service_role;
ALTER TABLE public.accessibility_compliance ENABLE ROW LEVEL SECURITY;
CREATE POLICY "accessibility_compliance_staff_all" ON public.accessibility_compliance FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss'));
CREATE TABLE IF NOT EXISTS public.audit_logs (action text, id uuid PRIMARY KEY DEFAULT gen_random_uuid(), meta_json jsonb, module text, role text, timestamp text, user_id text);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.audit_logs TO authenticated; GRANT ALL ON public.audit_logs TO service_role;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "audit_logs_staff_all" ON public.audit_logs FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss'));
CREATE TABLE IF NOT EXISTS public.business_categories (created_at timestamptz DEFAULT now(), description text, display_order numeric, icon text, id uuid PRIMARY KEY DEFAULT gen_random_uuid(), is_active boolean, name text, updated_at timestamptz DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.business_categories TO authenticated; GRANT ALL ON public.business_categories TO service_role;
ALTER TABLE public.business_categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "business_categories_staff_all" ON public.business_categories FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss'));
CREATE TABLE IF NOT EXISTS public.demo_alerts (acknowledged_at timestamptz, acknowledged_by text, action_taken text, alert_type text, created_at timestamptz DEFAULT now(), demo_id text, escalated_to text[], id uuid PRIMARY KEY DEFAULT gen_random_uuid(), is_active boolean, message text, requires_action boolean);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demo_alerts TO authenticated; GRANT ALL ON public.demo_alerts TO service_role;
ALTER TABLE public.demo_alerts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "demo_alerts_staff_all" ON public.demo_alerts FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss'));
CREATE TABLE IF NOT EXISTS public.demo_analytics (avg_duration_seconds numeric, bounce_rate numeric, conversion_count numeric, conversion_rate numeric, created_at timestamptz DEFAULT now(), date text, demo_id text, device_breakdown jsonb, id uuid PRIMARY KEY DEFAULT gen_random_uuid(), region_breakdown jsonb, top_pages jsonb, total_views numeric, unique_views numeric);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demo_analytics TO authenticated; GRANT ALL ON public.demo_analytics TO service_role;
ALTER TABLE public.demo_analytics ENABLE ROW LEVEL SECURITY;
CREATE POLICY "demo_analytics_staff_all" ON public.demo_analytics FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss'));
CREATE TABLE IF NOT EXISTS public.demo_categories (created_at timestamptz DEFAULT now(), description text, display_order numeric, icon text, id uuid PRIMARY KEY DEFAULT gen_random_uuid(), is_active boolean, name text);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demo_categories TO authenticated; GRANT ALL ON public.demo_categories TO service_role;
ALTER TABLE public.demo_categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "demo_categories_staff_all" ON public.demo_categories FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss'));
CREATE TABLE IF NOT EXISTS public.demo_clicks (browser text, city text, clicked_at timestamptz, converted boolean, country text, demo_id text, device_type text, franchise_id text, id uuid PRIMARY KEY DEFAULT gen_random_uuid(), ip_address text, referrer text, region text, reseller_id text, session_duration numeric, user_id text, user_role text);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demo_clicks TO authenticated; GRANT ALL ON public.demo_clicks TO service_role;
ALTER TABLE public.demo_clicks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "demo_clicks_staff_all" ON public.demo_clicks FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss'));
CREATE TABLE IF NOT EXISTS public.demo_deployments (approved_domain text, approved_ips text[], blocked_attempts numeric, created_at timestamptz DEFAULT now(), created_by text, daily_demo_id text, demo_id text, deployment_status text, encryption_key_ref text, expires_at timestamptz, id uuid PRIMARY KEY DEFAULT gen_random_uuid(), is_active boolean, is_domain_locked boolean, is_encrypted boolean, is_obfuscated boolean, last_verification_at timestamptz, license_key text, license_key_hash text, order_id text, verification_count numeric);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demo_deployments TO authenticated; GRANT ALL ON public.demo_deployments TO service_role;
ALTER TABLE public.demo_deployments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "demo_deployments_staff_all" ON public.demo_deployments FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss'));
CREATE TABLE IF NOT EXISTS public.demo_escalations (acknowledged_at timestamptz, alert_id text, auto_escalated boolean, created_at timestamptz DEFAULT now(), demo_id text, escalated_to_role text, escalated_to_user text, escalation_level numeric, id uuid PRIMARY KEY DEFAULT gen_random_uuid(), reason text, resolution_notes text, resolved_at timestamptz, status text);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demo_escalations TO authenticated; GRANT ALL ON public.demo_escalations TO service_role;
ALTER TABLE public.demo_escalations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "demo_escalations_staff_all" ON public.demo_escalations FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss'));
CREATE TABLE IF NOT EXISTS public.demo_health (checked_at timestamptz, demo_id text, error_message text, id uuid PRIMARY KEY DEFAULT gen_random_uuid(), response_time numeric, status text);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demo_health TO authenticated; GRANT ALL ON public.demo_health TO service_role;
ALTER TABLE public.demo_health ENABLE ROW LEVEL SECURITY;
CREATE POLICY "demo_health_staff_all" ON public.demo_health FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss'));
CREATE TABLE IF NOT EXISTS public.demo_login_credentials (created_at timestamptz DEFAULT now(), demo_id text, id uuid PRIMARY KEY DEFAULT gen_random_uuid(), is_active boolean, login_url text, notes text, password text, role_type text, username text);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demo_login_credentials TO authenticated; GRANT ALL ON public.demo_login_credentials TO service_role;
ALTER TABLE public.demo_login_credentials ENABLE ROW LEVEL SECURITY;
CREATE POLICY "demo_login_credentials_staff_all" ON public.demo_login_credentials FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss'));
CREATE TABLE IF NOT EXISTS public.demo_login_roles (created_at timestamptz DEFAULT now(), created_by text, demo_id text, display_order numeric, id uuid PRIMARY KEY DEFAULT gen_random_uuid(), is_active boolean, password_encrypted text, role_name text, updated_at timestamptz DEFAULT now(), username text);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demo_login_roles TO authenticated; GRANT ALL ON public.demo_login_roles TO service_role;
ALTER TABLE public.demo_login_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "demo_login_roles_staff_all" ON public.demo_login_roles FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss'));
CREATE TABLE IF NOT EXISTS public.demo_renewal_logs (auto_renewed boolean, created_at timestamptz DEFAULT now(), demo_id text, id uuid PRIMARY KEY DEFAULT gen_random_uuid(), new_expiry text, notes text, previous_expiry text, renewed_by text);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demo_renewal_logs TO authenticated; GRANT ALL ON public.demo_renewal_logs TO service_role;
ALTER TABLE public.demo_renewal_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "demo_renewal_logs_staff_all" ON public.demo_renewal_logs FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss'));
CREATE TABLE IF NOT EXISTS public.demo_report_cards (action_timestamp text, action_type text, auto_registered boolean, completion_time_seconds numeric, created_at timestamptz DEFAULT now(), demo_id text, demo_name text, demo_status text, error_details text, fix_details text, id uuid PRIMARY KEY DEFAULT gen_random_uuid(), new_values jsonb, old_values jsonb, performed_by text, performed_by_role text, sector text, sub_category text, uptime_state text, workflow_status text);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demo_report_cards TO authenticated; GRANT ALL ON public.demo_report_cards TO service_role;
ALTER TABLE public.demo_report_cards ENABLE ROW LEVEL SECURITY;
CREATE POLICY "demo_report_cards_staff_all" ON public.demo_report_cards FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss'));
CREATE TABLE IF NOT EXISTS public.demo_requests (client_email text, client_name text, company_name text, created_at timestamptz DEFAULT now(), id uuid PRIMARY KEY DEFAULT gen_random_uuid(), interested_category text, message text, notes text, phone text, responded_at timestamptz, responded_by text, status text);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demo_requests TO authenticated; GRANT ALL ON public.demo_requests TO service_role;
ALTER TABLE public.demo_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "demo_requests_staff_all" ON public.demo_requests FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss'));
CREATE TABLE IF NOT EXISTS public.demo_validation_logs (created_at timestamptz DEFAULT now(), demo_id text, demo_url text, error_message text, http_status numeric, id uuid PRIMARY KEY DEFAULT gen_random_uuid(), response_time_ms numeric, status text, validated_at timestamptz, validated_by text, validation_type text);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demo_validation_logs TO authenticated; GRANT ALL ON public.demo_validation_logs TO service_role;
ALTER TABLE public.demo_validation_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "demo_validation_logs_staff_all" ON public.demo_validation_logs FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss'));
CREATE TABLE IF NOT EXISTS public.demos (activated_at timestamptz, activated_by text, ai_category_suggestion text, ai_tech_suggestion text, backup_url text, category text, category_id text, created_at timestamptz DEFAULT now(), created_by text, demo_banner_text text, demo_type text, description text, disable_destructive boolean, disable_exports boolean, expiry_date text, health_check_interval numeric, health_score numeric, http_status numeric, id uuid PRIMARY KEY DEFAULT gen_random_uuid(), is_bulk_created boolean, is_trending boolean, last_health_check text, last_verified_at timestamptz, lifecycle_status text, login_url text, masked_url text, max_concurrent_logins numeric, multi_login_enabled boolean, normalized_url text, renewal_date text, response_time_ms numeric, status text, tech_stack text, technology_id text, title text, total_login_roles numeric, updated_at timestamptz DEFAULT now(), uptime_percentage numeric, url text, verification_status text, video_fallback_url text);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.demos TO authenticated; GRANT ALL ON public.demos TO service_role;
ALTER TABLE public.demos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "demos_staff_all" ON public.demos FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss'));
CREATE TABLE IF NOT EXISTS public.product_action_logs (action text, action_details jsonb, created_at timestamptz DEFAULT now(), id uuid PRIMARY KEY DEFAULT gen_random_uuid(), performed_by text, performer_role text, product_id text, product_name text);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.product_action_logs TO authenticated; GRANT ALL ON public.product_action_logs TO service_role;
ALTER TABLE public.product_action_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "product_action_logs_staff_all" ON public.product_action_logs FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss'));
CREATE TABLE IF NOT EXISTS public.product_demo_mappings (demo_id text, id uuid PRIMARY KEY DEFAULT gen_random_uuid(), linked_at timestamptz, linked_by text, product_id text);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.product_demo_mappings TO authenticated; GRANT ALL ON public.product_demo_mappings TO service_role;
ALTER TABLE public.product_demo_mappings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "product_demo_mappings_staff_all" ON public.product_demo_mappings FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss'));
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS abuse_reported boolean;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS additional_files jsonb;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS blog_url text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS business_category_id text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS canonical_url text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS changelog text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS compatibility text[];
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS conversion_count numeric;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS coupon_code text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS created_by text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS deleted_at timestamptz;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS demo_click_count numeric;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS demo_credentials jsonb;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS demo_embed text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS demo_type text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS demo_url text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS demo_video_url text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS difficulty_level text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS discount_price numeric;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS documentation_url text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS dynamic_pricing jsonb;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS feature_list text[];
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS featured_rank numeric;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS features_json jsonb;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS gallery_urls text[];
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS has_broken_demo boolean;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS industry_tags text[];
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS installation_guide text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS is_active boolean;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS is_featured boolean;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS is_free boolean;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS is_new boolean;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS is_subscription boolean;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS keywords text[];
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS last_updated_at timestamptz;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS license_tier text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS license_type text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS lifetime_price numeric;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS main_file_url text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS manual_rank numeric;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS meta_description text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS meta_title text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS monthly_price numeric;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS og_description text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS og_image text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS og_title text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS popular_score numeric;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS preview_urls text[];
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS pricing_model text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS product_id text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS product_name text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS product_type text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS release_notes text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS requirements text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS review_flagged boolean;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS search_keywords text[];
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS sections_json jsonb;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS short_description text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS slug text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS subcategory_id text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS support_response_time text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS support_url text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS synonyms text[];
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS tags text[];
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS tech_stack text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS tech_stack_tags text[];
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS thumbnail_url text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS trending boolean;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS use_case_tags text[];
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS verified_author boolean;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS video_thumbnail_url text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS view_count numeric;
CREATE TABLE IF NOT EXISTS public.server_backups (backup_name text, backup_type text, checksum text, completed_at timestamptz, created_at timestamptz DEFAULT now(), encryption_enabled boolean, encryption_key_id text, error_message text, expires_at timestamptz, id uuid PRIMARY KEY DEFAULT gen_random_uuid(), is_auto_backup boolean, metadata jsonb, restore_point_id text, retention_days numeric, server_id text, size_gb numeric, started_at timestamptz, status text, storage_location text, triggered_by text);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.server_backups TO authenticated; GRANT ALL ON public.server_backups TO service_role;
ALTER TABLE public.server_backups ENABLE ROW LEVEL SECURITY;
CREATE POLICY "server_backups_staff_all" ON public.server_backups FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss'));
CREATE TABLE IF NOT EXISTS public.software_catalog (base_price numeric, category text, created_at timestamptz DEFAULT now(), demo_id text, demo_url text, id uuid PRIMARY KEY DEFAULT gen_random_uuid(), is_demo_registered boolean, name text, type text, updated_at timestamptz DEFAULT now(), vendor text);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.software_catalog TO authenticated; GRANT ALL ON public.software_catalog TO service_role;
ALTER TABLE public.software_catalog ENABLE ROW LEVEL SECURITY;
CREATE POLICY "software_catalog_staff_all" ON public.software_catalog FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'boss'));